### PR TITLE
Update jdbc dependency for nodejs 12+

### LINKED ISSUE #56: node-teradata relies on old version of JDBC
node-teradata is using an old version of JDBC that uses an older version of java. 
Can we have the version of JDBC updated to 0.7.0 in the dependencies to use the newest version of java (0.12.1) instead of (0.11.1) which has a issues with node-gyp

### PR DESCRIPTION
**Pull request by ericdotdata**
I was getting compile issues with `java` on the 1.6.0 version which has the `0.6.x` branch of jdbc.  Updating to the 0.7.x seems to fix this.

*Edit* this should resolve https://github.com/2Toad/node-teradata/issues/56

### CODE REVIEW

**Comment by JasonPierce** [comment]
@ericdotdata thanks for submitting the PR. Looks good. Will you please add Node v12 to the [.travis.yml](https://github.com/ramencloud/node-teradata/blob/update-versions/.travis.yml) file?

**Comment by ericdotdata** [comment]
> @ericdotdata thanks for submitting the PR. Looks good. Will you please add Node v12 to the [.travis.yml](https://github.com/ramencloud/node-teradata/blob/update-versions/.travis.yml?rgh-link-date=2021-03-01T20%3A22%3A04Z) file?

done, thanks!

**Comment by ericdotdata** [comment]
@JasonPierce is there any way for me to view the travis results?

**Comment by JasonPierce** [comment]
@ericdotdata I noticed Travis-CI hadn't updated the status since you created the PR (5 days ago), so I hopped over to Travis-CI. Looks like it was having a migration issue from travis-ci.org to travis-ci.com. I kicked off the migration again -- should be visible to you once it updates (ETA 30m I'm told).

Until the update comes through, you can see the status here: https://travis-ci.com/github/2Toad/node-teradata/pull_requests

**Comment by ericdotdata** [comment]
@JasonPierce thanks boss!

**Comment by ericdotdata** [comment]
@JasonPierce looks like it timed out, so I just re-created the last commit and it looks like it ran successfully (and almost immediately this time): https://travis-ci.com/github/2Toad/node-teradata/builds/218667711

**Comment by ericdotdata** [comment]
@JasonPierce I updated the version to 1.7.0 do you want me to revert that so you can update it, or is this PR going to be sufficient to cut a release?

**Comment by JasonPierce** [comment]
> I updated the version to 1.7.0 do you want me to revert that so you can update it, or is this PR going to be sufficient to cut a release?

Yes, please revert the version bump -- I'll do that in a separate commit. 

I had originally targeted Issue #56 as a v2.0.0 release, as I was worried it would cause a breaking change, but having read through the jdbc 0.7.4 docs, it looks like it's backwards compatible with 0.6.4

**Comment by ericdotdata** [comment]
@JasonPierce rebased, and removed the version bump, let me know if there is anything else.  And yes, my understanding is the jdbc 0.7 is backward compatible, so from my perspective this should be good-to-go

**Comment by ericdotdata** [comment]
@JasonPierce ping

**Review by JasonPierce — APPROVED** [review]

**Comment by JasonPierce** [comment]
Thanks for the reminder @ericdotdata! Your fix has been included in release [1.6.1](https://github.com/2Toad/node-teradata/releases/tag/v1.6.1), which is now live

**Comment by ericdotdata** [comment]
@JasonPierce thank you!

**Pull request merged**
